### PR TITLE
Task 30 Admin School Profiles

### PR DESCRIPTION
**Pull request by carolineychen8**
https://www.notion.so/h4i/Achieve-Now-f2de8b1197594b959700bf4d169fdce4?p=d74f5b49f68648b4808d801f54593515&pm=s

### CODE REVIEW

**Comment by annabay04** [comment]
Slacked comments, waiting for fixes!

**Comment by zhouhelena** [comment]
Slacked - Anna's edits & not compiling, some problems here:
image

**Comment by zhouhelena** [comment]
Slacked - please add error handling & messaging

**Comment by zhouhelena** [comment]
[Slacked edits](https://hack4impact-penn.slack.com/archives/C0650ACDMBJ/p1701189388048949)

**Pull request merged**
